import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {openStore} from './storage.js';
import * as provider from './smartpay.js';
import {createApp} from './app.js';
const dir=path.dirname(fileURLToPath(import.meta.url));
const port=process.env.PORT||3000;
const store=openStore(process.env.DATA_DIR||path.join(dir,'data'));
const secret=store.signingSecret(process.env.UNLOCK_SECRET);
const app=createApp({store,provider,secret,baseURL:process.env.PUBLIC_BASE_URL||`http://localhost:${port}`,prices:{single:Number(process.env.PRICE_SINGLE||7.90),unlimited:Number(process.env.PRICE_UNLIMITED||24.90)}});
const server=app.listen(port,'0.0.0.0',()=>console.log(`CubeSolve API listening on ${port}; SmartPay ${provider.configured()?provider.mode():'missing: '+provider.missingConfiguration().join(', ')}`));
for(const signal of ['SIGTERM','SIGINT'])process.once(signal,()=>server.close(()=>{store.close();process.exit(0);}));
